/**
 * Cross-validation tests against Go-generated test vectors.
 *
 * These tests verify that the TypeScript crypto output is byte-identical
 * to Go's pkg/keys/canton_keys.go. If any test fails, the snap will NOT
 * produce signatures Canton accepts.
 *
 * Vectors are generated by: go run ./cmd/generate-test-vectors
 * in the canton-middleware repo.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { resolve } from "path";
import { compressedPubKeyToSPKIDer } from "../src/spki.js";
import { fingerprintFromSPKI } from "../src/fingerprint.js";
import { signHashDER } from "../src/sign.js";

interface SignatureVector {
  hash: string;
  der_signature: string;
}

interface KeyVector {
  private_key: string;
  compressed_public_key: string;
  spki_der: string;
  fingerprint: string;
  signatures: SignatureVector[];
}

interface VectorFile {
  description: string;
  vectors: KeyVector[];
}

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

const vectorsPath = resolve(import.meta.dirname!, "vectors.json");
const vectors: VectorFile = JSON.parse(readFileSync(vectorsPath, "utf-8"));

describe("cross-validation with Go test vectors", () => {
  for (const vec of vectors.vectors) {
    const keyLabel = vec.private_key.substring(0, 8) + "...";

    describe(`key ${keyLabel}`, () => {
      const compressedPubKey = hexToBytes(vec.compressed_public_key);

      it("SPKI DER encoding matches Go output", () => {
        const spkiDer = compressedPubKeyToSPKIDer(compressedPubKey);
        expect(bytesToHex(spkiDer)).toBe(vec.spki_der);
      });

      it("fingerprint matches Go output", () => {
        const spkiDer = hexToBytes(vec.spki_der);
        const fingerprint = fingerprintFromSPKI(spkiDer);
        expect(fingerprint).toBe(vec.fingerprint);
      });

      for (const sigVec of vec.signatures) {
        const hashLabel = sigVec.hash.substring(0, 8) + "...";

        it(`DER signature matches Go output for hash ${hashLabel}`, () => {
          const privateKey = hexToBytes(vec.private_key);
          const hash = hexToBytes(sigVec.hash);
          const derSig = signHashDER(privateKey, hash);
          expect(bytesToHex(derSig)).toBe(sigVec.der_signature);
        });
      }
    });
  }
});

describe("edge cases", () => {
  it("rejects wrong-length compressed public key", () => {
    expect(() => compressedPubKeyToSPKIDer(new Uint8Array(32))).toThrow();
  });

  it("rejects wrong-length private key", () => {
    expect(() => signHashDER(new Uint8Array(31), new Uint8Array(32))).toThrow();
  });

  it("rejects wrong-length hash", () => {
    expect(() => signHashDER(new Uint8Array(32), new Uint8Array(31))).toThrow();
  });
});
